name: "dradis-ce"

services:
  web:
    image: dradis/dradis-ce:latest
    volumes:
      # Persist the database
      - dradis-ce-storage:/dradis/storage
    ports:
      - 443:443
      - 80:80
    env_file:
      - path: .env
        required: false
    healthcheck:
      test: [
        "CMD-SHELL",
        "if [ \"$TLS_DOMAIN\" ]; then curl -f -k http://$TLS_DOMAIN/up; else curl -f http://localhost/up; fi"
      ]
      timeout: 15s
      retries: 3
volumes:
  dradis-ce-storage:
